### ISSUE TITLE
Author of Macrosiphum (M.) hellebori

### ISSUE THREAD

**Issue by KimberiP** [sfg-taxonpages/aphid#2]
The Australian Faunal Directory gives the author of this species as Theobald & Walton.
The reference is : Theobald, F.V. & Walton, C.L. 1923. A preliminary list of the Aphididae of North Wales, with descriptions of three new species. Annual Report and Proceedings of the Lancashire and Cheshire Entomological Society 1921-1922: 52-64
see https://biodiversity.org.au/afd/publication/6c9bdd8c-dc14-4f63-ba8c-e8ff049ba46c

**Comment by ColinFavret** [comment]
Hi @KimberiP , thank you so much for tracking down this reference! I found the article via interlibary loan and have updated [the entry in ASF](https://aphid.speciesfile.org/otus/913761/overview). Sorry it took a while to reply: I thought I'd get automatic notifications when someone opened an issue here. Please contribute as much as you wish: I'll make sure to stay on top of things from here on out! Cheers
